services:

####### FRONTEND ########
  frontend:
    image: pictonregistry.azurecr.io/frontend:latest
    environment: 
      - NODE_ENV=development
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    command: ["npm", "run", "preview"]

####### BACKEND ########
  backend:
    image: pictonregistry.azurecr.io/backend:latest  # ✅ Correct indentation
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      database:
        condition: service_healthy

####### POSTGRESQL ########
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
