services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map to port 3000 for frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - VITE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Django runs on port 8000
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    restart: always
    networks:
      - app-network
    command: python manage.py runserver 0.0.0.0:8000

networks:
  app-network:
    driver: bridge
